language: go
go: "1.14"
env:
  - GO111MODULE=on
script:
  - make test
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o imago-linux-amd64
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o imago-darwin-amd64
deploy:
  provider: releases
  api_key:
    secure: mWeF567IxQ38q5YxoaW2cRzLBNbC2JSfWZ82/VCsnApjqwMYoyS/+L6VMcmnMytlJyRhxuoPcqIQcF5lkRElZ9J84m/xBGRS+aQb0rEf3I1zqLYisNlsLhBnw05URUrYQwIqggFtjNW86VdAb+UvqdIZVaAuWiz+FJ6aziGrNyO0OqHh1Yq+eEFwXLAsygW+hJSMiuaYLq91h2+4MwqCjvv3WDB1mNow+Xjw5BgqhBA7xRWDbiJmKDv+c1iuFoR3wrXgQcknaY2UFFoZZ6fkxfzRfbtIA+TJ7MhlJN6W57ONwbe4gXEy4kcnAH6m406kADiWnqzF7TliT9NVzUDYndGXlaRiHRcpzW/CvD5aKya2NDOMk3EjVyGX4Zd8TwThE6hs0sNupR1pnB9KQ9GhFwZ+qHRDVLSdtOt6xLUW488ICJ4thSt4yBlsGLhT9x9gplVxb9sF/QcQbKvRxJHaM3LZ37GPgr9ZfQi39q/JBo7ieNi2jW8itO7E077W7YkDxO62L0Yof26jJJK6DXBMbwAMvJ4dTVLkm7cm+bo60nIl++0XxaYUMEaKaoUjKaDP5xIjYp1k/orCgDMhP7d4MZ26bgd3yUQ+GD/zWAkD2u0hxq1mxFhqEgMPNmozZx54XkBqVKCQCV9asA7qi4tsdlE2ILIFIDlQ7VCl1ESnGVw=
  skip_cleanup: true
  file:
    - imago-linux-amd64
    - imago-darwin-amd64
  on:
    tags: true
