---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imago
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imago
rules:
  - apiGroups:
      - ""
      - apps
    resources:
    - pods
    - replicasets
    verbs:
    - list
  - apiGroups:
      - ""
    resources:
    - secrets
    verbs:
    - get
  - apiGroups:
      - ""
      - apps
    resources:
      - daemonsets
      - deployments
    verbs:
      - get
      - list
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imago
roleRef:
  kind: ClusterRole
  name: imago
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: imago
    namespace: default
